version: "3.9"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - LANG=C.UTF-8
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    command: 'mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    hostname: mysqldb
    networks:
      dockbank_net:
        aliases:
          - mysqldb

  backend:
    build:
      context: ./backbank
      dockerfile: ../backbank/Dockerfile
    env_file: ./.env
    environment:
      - DB_HOST=mysqldb
      - DB_USERNAME=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_PASSWORD
      - DB_DATABASE=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on:
      - mysqldb
    networks:
      - dockbank_net

  frontend:
    build:
      context: ./frontbank
      dockerfile: ../frontbank/Dockerfile
    env_file: ./.env
    environment:
      - BACKEND_NODE_HOST=$NODE_HOST
      - BACKEND_NODE_PORT=$NODE_LOCAL_PORT
    ports:
      - $NODE_ANGULAR_PORT:$NGINX_PORT
    networks:
      - frontbank_net
      - dockbank_net

volumes:
  db:

networks:
  dockbank_net:
    external: true
  
  frontbank_net:
    driver: bridge